name: ci

on: 
  push:
    branches: [ master ]

jobs:
  macos_stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Build
      run: ./build-darwin-universal.sh
    - name: Run tests
      run: cargo test